# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/FPGA thi/Cu3/Sine_Rom/Sine_Rom.cache/wt} [current_project]
set_property parent.project_path {D:/FPGA thi/Cu3/Sine_Rom/Sine_Rom.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/FPGA thi/Cu3/Sine_Rom/Sine_Rom.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/FPGA thi/Câu2/clock_disp/clock_disp.srcs/sources_1/imports/new/chia_clk.v}
  {D:/FPGA thi/Câu3/hinhsin_rom/hinhsin_rom.srcs/sources_1/new/rom.v}
  {D:/FPGA thi/Câu3/hinhsin_rom/hinhsin_rom.srcs/sources_1/new/123.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/FPGA thi/Câu3/hinhsin_rom/hinhsin_rom.srcs/sources_1/cstr/sine_wave_const.xdc}}
set_property used_in_implementation false [get_files {{D:/FPGA thi/Câu3/hinhsin_rom/hinhsin_rom.srcs/sources_1/cstr/sine_wave_const.xdc}}]


synth_design -top sine_wave -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sine_wave.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sine_wave_utilization_synth.rpt -pb sine_wave_utilization_synth.pb"
