create_clock  -period 20 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports dot]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig_sel[5]}]

set_property PACKAGE_PIN J5 [get_ports {seg7_out[0]}]
set_property PACKAGE_PIN M3 [get_ports {seg7_out[1]}]
set_property PACKAGE_PIN J6 [get_ports {seg7_out[2]}]
set_property PACKAGE_PIN H5 [get_ports {seg7_out[3]}]
set_property PACKAGE_PIN G4 [get_ports {seg7_out[4]}]
set_property PACKAGE_PIN K6 [get_ports {seg7_out[5]}]
set_property PACKAGE_PIN K3 [get_ports {seg7_out[6]}]
set_property PACKAGE_PIN H4 [get_ports dot]
set_property PACKAGE_PIN M2 [get_ports {dig_sel[0]}]
set_property PACKAGE_PIN N4 [get_ports {dig_sel[1]}]
set_property PACKAGE_PIN L5 [get_ports {dig_sel[2]}]
set_property PACKAGE_PIN L4 [get_ports {dig_sel[3]}]
set_property PACKAGE_PIN M16 [get_ports {dig_sel[4]}]
set_property PACKAGE_PIN M17 [get_ports {dig_sel[5]}]

set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN M13 [get_ports rstn]
set_property PACKAGE_PIN K14 [get_ports up]
set_property PACKAGE_PIN K13 [get_ports down]


set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN G15 [get_ports uart_rx]

set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN G16 [get_ports uart_tx]