create_clock -period 20.000 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sin_out[7]}]

set_property PACKAGE_PIN D16 [get_ports {sin_out[0]}]
set_property PACKAGE_PIN F14 [get_ports {sin_out[1]}]
set_property PACKAGE_PIN E14 [get_ports {sin_out[2]}]
set_property PACKAGE_PIN D15 [get_ports {sin_out[3]}]
set_property PACKAGE_PIN B13 [get_ports {sin_out[4]}]
set_property PACKAGE_PIN A14 [get_ports {sin_out[5]}]
set_property PACKAGE_PIN C15 [get_ports {sin_out[6]}]
set_property PACKAGE_PIN A16 [get_ports {sin_out[7]}]

set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN M13 [get_ports rstn]
set_property PACKAGE_PIN K14 [get_ports up]
set_property PACKAGE_PIN K13 [get_ports down]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sin_out_OBUF[0]} {sin_out_OBUF[1]} {sin_out_OBUF[2]} {sin_out_OBUF[3]} {sin_out_OBUF[4]} {sin_out_OBUF[5]} {sin_out_OBUF[6]} {sin_out_OBUF[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
