create_clock  -period 20 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports mod]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst_IBUF] 
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets mod_IBUF] 

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports dot]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_sel[5]}]

set_property PACKAGE_PIN J5 [get_ports {led[0]}]
set_property PACKAGE_PIN M3 [get_ports {led[1]}]
set_property PACKAGE_PIN J6 [get_ports {led[2]}]
set_property PACKAGE_PIN H5 [get_ports {led[3]}]
set_property PACKAGE_PIN G4 [get_ports {led[4]}]
set_property PACKAGE_PIN K6 [get_ports {led[5]}]
set_property PACKAGE_PIN K3 [get_ports {led[6]}]
set_property PACKAGE_PIN H4 [get_ports dot]

set_property PACKAGE_PIN M2 [get_ports {led_sel[0]}]
set_property PACKAGE_PIN N4 [get_ports {led_sel[1]}]
set_property PACKAGE_PIN L5 [get_ports {led_sel[2]}]
set_property PACKAGE_PIN L4 [get_ports {led_sel[3]}]
set_property PACKAGE_PIN M16 [get_ports {led_sel[4]}]
set_property PACKAGE_PIN M17 [get_ports {led_sel[5]}]

set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN M13 [get_ports rst]
set_property PACKAGE_PIN K14 [get_ports mod]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
