webtalk_init -webtalk_dir C:/Users/Admin/Desktop/verilog/parallel_to_serial/parallel_to_serial.sim/sim_1/behav/xsim/xsim.dir/tb_parallel_to_serial_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 27 13:18:28 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6c3f0f6d-4241-4ca5-a1e1-f12fa7efd2e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8200f5e99e954e48808e5ad355a75cb8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 601497217 -regid "" -xml C:/Users/Admin/Desktop/verilog/parallel_to_serial/parallel_to_serial.sim/sim_1/behav/xsim/xsim.dir/tb_parallel_to_serial_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Admin/Desktop/verilog/parallel_to_serial/parallel_to_serial.sim/sim_1/behav/xsim/xsim.dir/tb_parallel_to_serial_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Admin/Desktop/verilog/parallel_to_serial/parallel_to_serial.sim/sim_1/behav/xsim/xsim.dir/tb_parallel_to_serial_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
